package:
  name: landmarkerio
  version: {{ environ['CONDACI_VERSION'] }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt && python setup.py sdist

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo<0.12.0
    - menpo3d
    - flask>=1
    - flask-restful
    - cherrypy
    - joblib
    - pyyaml

test:
  imports:
    - landmarkerio

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
